---
name: Eval-Context
version: 0.06
author:
  - 'Khemir Nadim ibn Hamouda. <nadim@khemir.net>'
abstract: "Evalute perl code in context wrapper\n"
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::Compare: 0
  Data::Dumper: 0
  Data::TreeDumper: 0
  Directory::Scratch::Structured: 0
  File::Slurp: 0
  Package::Generator: 0
  Readonly: 0
  Safe: 0
  Sub::Exporter: 0
  Sub::Install: 0
  Symbol: 0
  Test::Block: 0
  Test::Dependencies: 0
  Test::Distribution: 0
  Test::Exception: 0
  Test::NoWarnings: 0
  Test::Output: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Spelling: 0
  Test::Strict: 0
  Test::Warn: 0
  version: 0.5
provides:
  Eval::Context:
    file: lib/Eval/Context.pm
    version: 0.06
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
